services:
  web:
    build: .
    image: pythonapp-basics:latest
    container_name: pythonapp-basics
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
